---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# dRCTpower

<!-- badges: start -->
<!-- badges: end -->

The `dRCT` package contains a Shiny app and other helper functions to help users choose a sample size for an RCT that will be analyzed using the `dRCT` package. The app generates a range of reasonable sample sizes based on an auxiliary dataset that will be used to improve the precision of the RCT estimates. These estimates are based on splitting an auxiliary dataset into different subgroups and calculating the necessary sample size if the RCT sample were to resemble that subgroup. 

## Installation

You can install the development version of `dRCTpower` from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("jaylinlowe/dRCTpower")
```

## Functions 

* `run_app`: This is the main function, used to run the Shiny app. All sample size calculations, as well as other useful exploratory features, are present in the app. 

* `get_samp_sizes`: This function returns the necessary sample sizes, with and without using auxiliary data in the analysis process, for subgroups defined by a variable in the dataset. If you wish to perform the sample size calculations without using the Shiny app and already know how you wish to define subgroups, use this function. 

* Subgroup functions: These are used in the Shiny app to generate the subgroups. If you wish to break observations into subgroups for other purposes or investigate different break options outside of the Shiny app, these functions may be useful.  

  * `numeric_subgroups`: Breaks up a numeric covariate into a specified number of approximately equally sized groups. 
  
  * `errror_subgroups`: Divides observations into subgroups based on predicted error. 
